# Generated by Django 3.1.4 on 2021-01-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight_tab',
            name='dont_be_late',
            field=models.TextField(blank=True, null=True),
        ),
    ]
