# Generated by Django 3.1.4 on 2021-01-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210101_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=12, verbose_name='nickname')),
                ('hp', models.FloatField(default=100)),
                ('damage', models.FloatField(default=27)),
            ],
        ),
    ]
