# Generated by Django 3.1.4 on 2021-01-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_stats',
            name='user_name',
            field=models.CharField(default='Your nickname', max_length=12, verbose_name='nickname'),
        ),
    ]
